import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

function Nav() {
  return <input className={"w-full"} type="checkbox"></input>;
}

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LangLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
